// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VaccinationCard.Infrastructure.Data;

#nullable disable

namespace VaccinationCard.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250822222632_First-Migration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VaccinationCard.Domain.Entities.DoseType", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("EntityId");

                    b.ToTable("DoseTypes");
                });

            modelBuilder.Entity("VaccinationCard.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EntityId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("VaccinationCard.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EntityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VaccinationCard.Domain.Entities.VaccinationRecord", b =>
                {
                    b.Property<Guid>("VaccineId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DoseTypeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("VaccinationDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("VaccineId", "DoseTypeId", "PersonId");

                    b.HasIndex("DoseTypeId");

                    b.ToTable("VaccinationRecords");
                });

            modelBuilder.Entity("VaccinationCard.Domain.Entities.Vaccine", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EntityId");

                    b.ToTable("Vaccines");
                });

            modelBuilder.Entity("VaccinationCard.Domain.Entities.VaccineDoseType", b =>
                {
                    b.Property<Guid>("VaccineId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DoseTypeId")
                        .HasColumnType("char(36)");

                    b.HasKey("VaccineId", "DoseTypeId");

                    b.HasIndex("DoseTypeId");

                    b.ToTable("VaccineDoseTypes");
                });

            modelBuilder.Entity("VaccinationCard.Domain.Entities.VaccinationRecord", b =>
                {
                    b.HasOne("VaccinationCard.Domain.Entities.DoseType", "DoseType")
                        .WithMany("VaccinationRecords")
                        .HasForeignKey("DoseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaccinationCard.Domain.Entities.Person", "Person")
                        .WithMany("VaccinationRecords")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaccinationCard.Domain.Entities.Vaccine", "Vaccine")
                        .WithMany("VaccineRecords")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoseType");

                    b.Navigation("Person");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("VaccinationCard.Domain.Entities.VaccineDoseType", b =>
                {
                    b.HasOne("VaccinationCard.Domain.Entities.DoseType", "DoseType")
                        .WithMany("VaccineDoseTypes")
                        .HasForeignKey("DoseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaccinationCard.Domain.Entities.Vaccine", "Vaccine")
                        .WithMany("VaccineDoseTypes")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoseType");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("VaccinationCard.Domain.Entities.DoseType", b =>
                {
                    b.Navigation("VaccinationRecords");

                    b.Navigation("VaccineDoseTypes");
                });

            modelBuilder.Entity("VaccinationCard.Domain.Entities.Person", b =>
                {
                    b.Navigation("VaccinationRecords");
                });

            modelBuilder.Entity("VaccinationCard.Domain.Entities.Vaccine", b =>
                {
                    b.Navigation("VaccineDoseTypes");

                    b.Navigation("VaccineRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
